feat: basic implement for RESP parser
wayslog/resp-parser pull request #1
Opened 2019-02-01 12:58 UTC by DCjanus

# Feature

+ Zero copy
+ Non-backtracking
+ Type safe

2019-02-11 11:16 UTC, wayslog requested changes
need more benchmarks and test cases

2019-02-11 11:16 UTC, wayslog commented on src/buffer.rs
> +use std::{cmp::min, io};
plz use `bytes::BytesMut`

2019-02-11 11:16 UTC, wayslog commented on src/lib.rs
> +// TODO integer overflow check
TODO...

2019-02-11 11:16 UTC, wayslog commented on src/lib.rs
> +                b'-' => self.0 = -self.0,
you call parse with default `IntegerParser`, but the initial value is `0`. And the negative value of zero is also zero!
so, if the data is `:-20\r\n`, you  will get a parsed integer as `20`, but not `-20`.

2019-02-11 11:16 UTC, wayslog commented on src/lib.rs
> +                b'-' => self.0 = -self.0,
bulk string's size gets only one way to negative: the whole bulk is `$-1\r\n`. So you should make it faster or test it.

2019-02-11 11:16 UTC, wayslog commented on src/lib.rs
> +                x @ b'0'..=b'9' => self.0 = self.0 * 10 + usize::from(x - b'0'),
you  should check if the array is `NULL array`, with content is `*-1\r\n`

2019-02-11 11:16 UTC, wayslog commented on src/lib.rs
> +        if data.pop() != Some(b'\r') {
inline command always ends with `\n` but not usually ends with `\r\n`. That's not error.

2019-02-11 11:16 UTC, wayslog commented on tests/basic.rs
> +
need more test case...

2019-02-13 07:40 UTC, wayslog commented
另外我还发现一个问题：如果是 Array 套 Array 的情况你这里没考虑啊。。。

2019-02-15 02:10 UTC, DCjanus commented
My code is shit, close this PR

2019-02-15 02:10 UTC, closed without merging